version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    links:
      - 'db:db'
    environment:
      APP_NAME: '${DOMAIN}'
      APP_URL: 'http://${DOMAIN}'
      CACHE_DRIVER: database
      CACHE_PREFIX: l_
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: your_mysql_root_password
      DB_DATABASE: laravel
    volumes:
      - './000-default.conf:/etc/apache2/sites-available/000-default.conf'
      - '.:/var/www/html'
      - /var/www/html/bootstrap/cache
    networks:
      put_net:
        ipv4_address: '${APP_IP}'
  db:
    image: 'mysql:5.7.22'
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      put_net:
        ipv4_address: '${DB_IP}'
networks:
  put_net:
    external:
      name: my-bridge-network
