version: '3'
services:

  database_server:
    image: mysql:8
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    env_file:
      - db.env
    volumes:
      - ./mysql-data:/var/lib/mysql
    user: "${U_ID}:${G_ID}"

  webserver:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: registry.gitlab.com/biscofil/thelios:user
    restart: unless-stopped
    tty: true
    depends_on:
      - database_server
    links:
      - "database_server:database_server"
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000" #php, for debug
      - "9001:9001" #php, for debug
      - "9003:9003" #php, for debug
    volumes:
      - './letsencrypt:/home/letsencrypt'
      - './000-default.conf:/etc/apache2/sites-available/000-default.conf'
      - './apache2.conf:/etc/apache2/apache2.conf'
      - '.:/var/www/html'
#      - /var/www/html/bootstrap/cache
    user: "${U_ID}:${G_ID}"

#  php-ws-client:
#    #    build:
#    #      context: .
#    #      dockerfile: Dockerfile
#    image: registry.gitlab.com/biscofil/thelios:user
#    restart: always
#    command: php artisan run_web_socket_client_loop
#    volumes:
#      - '.:/var/www/html'

  php-queue:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: registry.gitlab.com/biscofil/thelios:user
    restart: always
    depends_on:
      - webserver
      - database_server
    command: php artisan queue:work
    volumes:
      - '.:/var/www/html'

  cronjob:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: registry.gitlab.com/biscofil/thelios:user
    depends_on:
      - webserver
      - database_server
    command: ./run-scheduler.sh
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - '.:/var/www/html'

#  redis:
#    image: "redis:alpine"
#      user: "${U_ID}:${G_ID}"
