apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    label: kairos-database
  name: kairos-database
spec:
  replicas: 1
  selector:
    matchLabels:
      label: kairos-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        label: kairos-database
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: kairos-database-env
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kairos-secrets
                  key: DB_PASSWORD
          image: mysql:8
          name: kairos-database
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: kairos-database-claim
      restartPolicy: Always
      volumes:
        - name: kairos-database-claim
          persistentVolumeClaim:
            claimName: kairos-database-claim
status: {}
