apiVersion: v1
kind: Service
metadata:
  labels:
    label: {{.Values.database.serviceName}}
  name: {{.Values.database.serviceName}}
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    label: kairos-database
status:
  loadBalancer: {}
