apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kairos-database
  name: kairos-database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kairos-database
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kairos-database
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: kairos-database-db-env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: kairos-database-db-env
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  key: SERVICE_NAME
                  name: kairos-database-db-env
            - name: SERVICE_TAGS
              valueFrom:
                configMapKeyRef:
                  key: SERVICE_TAGS
                  name: kairos-database-db-env
          image: mysql:8
          name: kairos-database
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: kairos-database-claim
      restartPolicy: Always
      volumes:
        - name: kairos-database-claim
          persistentVolumeClaim:
            claimName: kairos-database-claim
status: {}
