apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kairos-webserver
  name: kairos-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kairos-webserver
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kairos-webserver
    spec:
      containers:
        - image: biscofil/kairos_php:webserver
          imagePullPolicy: Always
          name: kairos-webserver
          ports:
            - containerPort: 80
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /var/www/html/storage
              name: kairos-webserver-claim
          envFrom:
            - secretRef:
                name: kairos-webserver-secrets
      restartPolicy: Always
      volumes:
        - name: kairos-webserver-claim
          persistentVolumeClaim:
            claimName: kairos-webserver-claim
status: {}
