apiVersion: v1
kind: Service
metadata:
  labels:
    label: kairos-webserver-service
  name: kairos-webserver-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    label: kairos-webserver
status:
  loadBalancer: {}
