apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    label: kairos-webserver-claim
  name: kairos-webserver-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
