<?php


namespace App\Jobs;


use App\Models\Mix;
use App\Models\PeerServer;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;

/**
 * Class DownloadPeerMix
 * @package App\Jobs
 * @property Mix mixModel
 */
class DownloadPeerMix implements ShouldQueue
{

    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    public Mix $mixModel;

    /**
     * WaitAndRespond constructor.
     * @param \App\Models\Mix $mixModel
     */
    public function __construct(Mix $mixModel)
    {
        $this->mixModel = $mixModel;
    }

    /**
     * Execute the job.
     *
     * @return void
     * @throws \Exception
     */
    public function handle()
    {
        Log::debug('Downloading Mix');
        if ($this->mixModel->trustee->peer_server_id === PeerServer::meID) {
            Log::info('Mix download skipped : generated by current server');
            return;
        }
        $this->mixModel->download();
        Log::info('Mix downloaded');
    }
}
