on:
  push:
    branches:
    - main
    - release/*

jobs:
  php_db_test:
    runs-on: ubuntu-latest
    container:
      image: biscofil/kairos_php:no_user
      env:
        DB_DATABASE: laravel
        DB_PASSWORD: your_mysql_root_password
        DB_HOST: mysql
        DB_USERNAME: root
        QUEUE_CONNECTION: database

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: your_mysql_root_password
          DB_HOST: mysql
          DB_USERNAME: root

    steps:

    - uses: actions/checkout@v2

    - name: test php
      run: |
        cp .env.example .env
        cp db.env.example db.env
        composer install
        rm bootstrap/cache/*
        php artisan config:clear
        php artisan cache:clear
        php artisan route:clear
        php artisan view:clear
        php artisan key:generate
        php artisan migrate
        php artisan db:seed
        php artisan migrate:refresh
        php artisan db:seed
        php artisan generate:jwt-keypair
        php artisan config:cache
        php artisan route:cache
        echo PHPUNIT TEST
        vendor/phpunit/phpunit/phpunit tests/ --coverage-text --colors=never --configuration phpunit_gitlab.xml

  npm_test:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Setup Node.js
       uses: actions/setup-node@v2-beta
       with:
         node-version: '12'
         check-latest: true
     - name: Install NPM dependencies
       run: npm install
     - name: Test NPM compilation
       run: npm run prod
